sonar.projectKey=RomainNgd_collector_shop
sonar.projectName=collector-shop
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.sources=go-api,collector-spa/src
sonar.tests=go-api

sonar.test.inclusions=go-api/**/*_test.go
sonar.exclusions=collector-spa/build/**,collector-spa/.svelte-kit/**,collector-spa/node_modules/**,**/coverage/**,**/*.d.ts

sonar.go.coverage.reportPaths=go-api/coverage.out
