apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: collector-shop-prod
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - go-api.yaml
  - collector-spa.yaml
  - collector-spa-hpa.yaml
  - ingress.yaml
