apiVersion: v1
kind: Secret
metadata:
  name: collector-shop-secrets
  namespace: collector-shop-prod
type: Opaque
stringData:
  DB_NAME: ecommerce
  DB_USER: golang
  DB_PASSWORD: golang
  JWT_SECRET: change-me-before-real-prod
  STRIPE_SECRET_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""
