name: Reusable SonarCloud

on:
  workflow_call:
    inputs:
      sonar_organization:
        description: SonarCloud organization key
        required: true
        type: string
    secrets:
      sonar_token:
        required: true

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.sonar_token }}
      SONAR_ORGANIZATION: ${{ inputs.sonar_organization }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Go coverage
        uses: actions/download-artifact@v4
        with:
          name: go-coverage
          path: go-api

      - name: SonarCloud scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.qualitygate.wait=true
            -Dsonar.qualitygate.timeout=300
